---
title: "Untitled"
author: "Yon Ho Jee"
date: "2024-05-06"
output: html_document
---
```{r warning=FALSE}
library(data.table)
library(dplyr)
library(magrittr)
```

# cross-biobank rg output from LDSC
```{r}
df_res<-fread("/n/holylfs05/LABS/kraft_lab/Lab/yjee/ldsc/output/cross_biobank_rg/LMM/cross_biobank_rg_LMM.txt",data.table = F)
```

# 05.05.2024
# replace ukb estimates by Popcorn
# KCPS2-UKB cross-biobank rg output
```{r}
study_pair <- "kcps2ukb"
study_pair <- "ukbkcps2"

trait_list_overlap <- c("LDL","TG","HDL","CHO","FBS","GOT","GPT","GGT","BIL","ALB","CREAT","HB","HCT","RBC","WBC","PLT","SBP","DBP","WT","HEIGHT","BMI")

rg_out <- data.frame()
for(k in 1:(length(trait_list_overlap))){ 
  trait <- trait_list_overlap[k]

  rl <- fread(paste0("/n/holylfs05/LABS/kraft_lab/Lab/yjee/Popcorn/output/",study_pair,"/",trait,"_rg.txt"), data.table = F)
  rl$Trait <- trait
  
  data <- rl%>%pivot_wider(names_from = V1, values_from = `Val (obs)`:`P (Z)`) %>% as.data.frame()

  rg_out <- rbind(rg_out,data)
}


df_res$rg.ukb <- rg_out$`Val (obs)_pgi`
df_res$se.ukb <- rg_out$SE_pgi

df_res$z.ukb <- rg_out$Z_pgi
df_res$p.ukb <- rg_out$`P (Z)_pgi`

df_res$h2_obs.ukb <- rg_out$`Val (obs)_h2^2`
df_res$h2_obs_se.ukb <- rg_out$`SE_h2^2`

```

```{r}
fwrite(df_res,"/n/holylfs05/LABS/kraft_lab/Lab/yjee/Popcorn/output/Popcorn_rg_LMM.txt",sep = "\t")
```

# Plot h2
```{r warning=FALSE}
library(data.table)
library(tidyverse)
library(gridExtra)
library(grid)
#library(TigR)
library(ggrepel)
library(ggpubr)
```
```{r}
library(reshape2)

kcps2_h2<-fread('/n/holylfs05/LABS/kraft_lab/Lab/yjee/ldsc/output/SAIGE/LDSC_36_outputs.txt',data.table = F)
#kcps2_h2<-fread('/n/holylfs05/LABS/kraft_lab/Lab/yjee/ldsc/output/PLINK_irnt/LDSC_36_outputs_PLINK_irnt.txt',data.table = F)

kcps2_h2 <- separate(kcps2_h2, `Observed scale h2 (SE)`, into = c("h2_obs.kcps2", "a"), sep = " ")
kcps2_h2$h2_obs_se.kcps2 <- colsplit(string = gsub(pattern = "\\(|\\)",replacement = "",x = kcps2_h2$a),
     pattern = " ",names = c("h2_obs_se.kcps2",""))$h2_obs_se.kcps2
kcps2_h2 <- kcps2_h2 %>% filter(trait %in% trait_list_overlap)

kcps2_h2_res <- data.frame(cbind(kcps2_h2,df_res)) 
#kcps2_h2_res$trait <- trait_list_overlap
```

```{r}
df_res01 <- kcps2_h2_res %>% filter(h2_obs.kcps2>0.01 & 
                                      h2_obs.koges>0.01 & 
                                      h2_obs.bbj>0.01 &
                                      h2_obs.twb>0.01&  
                                      h2_obs.ukb>0.01)

c <- ggplot(data = kcps2_h2_res) +
  geom_point(aes(x= as.numeric(h2_obs.kcps2), y=as.numeric(h2_obs.koges), color="darkorange"), size=5) +
  geom_errorbarh(data = kcps2_h2_res, aes(xmin = as.numeric(h2_obs.kcps2)-1.96*h2_obs_se.kcps2, xmax = as.numeric(h2_obs.kcps2)+1.96*h2_obs_se.kcps2,y = as.numeric(h2_obs.koges), colour = "grey80")) + 
  geom_errorbar(data = kcps2_h2_res, aes(ymin = as.numeric(h2_obs.koges)-1.96*h2_obs_se.koges, ymax = as.numeric(h2_obs.koges)+1.96*h2_obs_se.koges, x = as.numeric(h2_obs.kcps2), colour = "grey80")) +

  geom_errorbarh(data = kcps2_h2_res, aes(xmin = as.numeric(h2_obs.kcps2)-1.96*h2_obs_se.kcps2, xmax = as.numeric(h2_obs.kcps2)+1.96*h2_obs_se.kcps2,y = as.numeric(h2_obs.bbj), colour = "grey80")) + 
  geom_errorbar(data = kcps2_h2_res, aes(ymin = as.numeric(h2_obs.bbj)-1.96*h2_obs_se.bbj, ymax = as.numeric(h2_obs.bbj)+1.96*h2_obs_se.bbj, x = as.numeric(h2_obs.kcps2), colour = "grey80")) +

  geom_errorbarh(data = kcps2_h2_res, aes(xmin = as.numeric(h2_obs.kcps2)-1.96*h2_obs_se.kcps2, xmax = as.numeric(h2_obs.kcps2)+1.96*h2_obs_se.kcps2,y = as.numeric(h2_obs.twb), colour = "grey80")) + 
  geom_errorbar(data = kcps2_h2_res, aes(ymin = as.numeric(h2_obs.twb)-1.96*h2_obs_se.twb, ymax = as.numeric(h2_obs.twb)+1.96*h2_obs_se.twb, x = as.numeric(h2_obs.kcps2), colour = "grey80")) +

  geom_errorbarh(data = kcps2_h2_res, aes(xmin = as.numeric(h2_obs.kcps2)-1.96*h2_obs_se.kcps2, xmax = as.numeric(h2_obs.kcps2)+1.96*h2_obs_se.kcps2,y = as.numeric(h2_obs.ukb), colour = "grey80")) + 
  geom_errorbar(data = kcps2_h2_res, aes(ymin = as.numeric(h2_obs.ukb)-1.96*h2_obs_se.ukb, ymax = as.numeric(h2_obs.ukb)+1.96*h2_obs_se.ukb, x = as.numeric(h2_obs.kcps2), colour = "grey80")) +
  
  geom_point(data = kcps2_h2_res, aes(x = as.numeric(h2_obs.kcps2), y = as.numeric(h2_obs.bbj), color="#C77CFF"), size=5) +
  
  geom_point(data = kcps2_h2_res, aes(x = as.numeric(h2_obs.kcps2), y = as.numeric(h2_obs.twb), color="#00BFC4"), size=5) +
  
  geom_point(data = kcps2_h2_res, aes(x = as.numeric(h2_obs.kcps2), y = as.numeric(h2_obs.ukb), color="green4"), size=5) +


  scale_color_manual(labels = c("KoGES","BBJ","TWB","UKB",""), values = c("darkorange","#C77CFF","#00BFC4","green4","grey80")) +
  
  geom_abline(intercept = 0, slope = 1, linetype="dotted") + 
  #geom_label_repel(aes(label=trait), size=4, box.padding = unit(0.5, "lines"))+
  theme(legend.title = element_blank()) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), 
      legend.title = element_blank(), 
      legend.position = c(0.8, 0.2), 
      legend.key=element_rect(fill="white"), legend.text = element_text(size=14),   axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14)) +
  #ggpubr::theme_pubr(border = TRUE) + 
xlab("Heritability in KCPS2") + ylab("Study-specific heritability")
```

# Plot rg
## EAS
```{r}
df_res01 <- kcps2_h2_res %>% filter(h2_obs.kcps2>0.01 & 
                                      h2_obs.koges>0.01 & 
                                      h2_obs.bbj>0.01 &
                                      h2_obs.twb>0.01&  
                                      h2_obs.ukb>0.01)
ss1 <- df_res01 %>%
  ggscatter(x="rg.bbj",y="rg.koges", size = 5, 
            label = "p1", repel = TRUE)+ 
  ggpubr::theme_pubr(border = TRUE) + theme(legend.position = "none") +
  geom_abline(intercept = 0, slope = 1, linetype="dotted") + 
  geom_errorbar(aes(ymin = rg.koges-1.96*se.koges, ymax = rg.koges+1.96*se.bbj), col="grey80") + 
  geom_errorbarh(aes(xmin = rg.bbj-1.96*se.bbj, xmax = rg.bbj+1.96*se.bbj), col="grey80") +
  theme(legend.title = element_blank()) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), 
      legend.title = element_blank(), 
      legend.position = c(0.8, 0.2), 
      legend.key=element_rect(fill="white"), legend.text = element_text(size=14),   axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14)) +
  xlim(0,1.5) + ylim(0,1.5) + xlab(bquote(~r[g]*" (KCPS2-BBJ)"))+ ylab(bquote(~r[g]*" (KCPS2-KoGES)"))

ss2 <- df_res01 %>%
  ggscatter(x="rg.twb",y="rg.bbj", size = 5, 
            label = "p1", repel = TRUE)+ 
  ggpubr::theme_pubr(border = TRUE) + theme(legend.position = "none") +
  geom_abline(intercept = 0, slope = 1, linetype="dotted") + 
  geom_errorbar(aes(ymin = rg.bbj-1.96*se.bbj, ymax = rg.bbj+1.96*se.bbj), col="grey80") + 
  geom_errorbarh(aes(xmin = rg.twb-1.96*se.twb, xmax = rg.twb+1.96*se.twb), col="grey80") +
  theme(legend.title = element_blank()) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), 
      legend.title = element_blank(), 
      legend.position = c(0.8, 0.2), 
      legend.key=element_rect(fill="white"), legend.text = element_text(size=14),   axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14)) +
  xlim(0,1.5) + ylim(0,1.5) + xlab(bquote(~r[g]*" (KCPS2-TWB)"))+ ylab(bquote(~r[g]*" (KCPS2-BBJ)"))


ss3 <- df_res01 %>%
  ggscatter(x="rg.koges",y="rg.twb", size = 5, 
            label = "p1", repel = TRUE)+ 
  ggpubr::theme_pubr(border = TRUE) + theme(legend.position = "none") +
  geom_abline(intercept = 0, slope = 1, linetype="dotted") + 
  geom_errorbar(aes(ymin = rg.twb-1.96*se.twb, ymax = rg.twb+1.96*se.twb), col="grey80") + 
  geom_errorbarh(aes(xmin = rg.koges-1.96*se.koges, xmax = rg.koges+1.96*se.koges), col="grey80") +
  theme(legend.title = element_blank()) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), 
      legend.title = element_blank(), 
      legend.position = c(0.8, 0.2), 
      legend.key=element_rect(fill="white"), legend.text = element_text(size=14),   axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14)) +
  xlim(0,1.5) + ylim(0,1.5) + xlab(bquote(~r[g]*" (KCPS2-KoGES)"))+ ylab(bquote(~r[g]*" (KCPS2-TWB)"))

#ggarrange(ss2,ss1,ss3,ncol=3, common.legend=T, legend="right", labels = c("A", "B", "C"))
bigss <- ggarrange(plotlist = list(ss1, ss2, ss3), ncol = 3, common.legend=T, legend="right", labels = c("a", "b", "c"))

```

## EUR
```{r}
df_res01 <- kcps2_h2_res %>% filter(h2_obs.kcps2>0.01 & 
                                      h2_obs.koges>0.01 & 
                                      h2_obs.bbj>0.01 &
                                      h2_obs.twb>0.01&  
                                      h2_obs.ukb>0.01)

u1 <- df_res01 %>%
  ggscatter(x="rg.bbj",y="rg.ukb", size = 5, 
            label = "p1", repel = TRUE)+ 
  ggpubr::theme_pubr(border = TRUE) + theme(legend.position = "none") +
  geom_abline(intercept = 0, slope = 1, linetype="dotted") + 
  geom_errorbar(aes(ymin = rg.ukb-1.96*se.ukb, ymax = rg.ukb+1.96*se.ukb), col="grey80") + 
  geom_errorbarh(aes(xmin = rg.bbj-1.96*se.bbj, xmax = rg.bbj+1.96*se.bbj), col="grey80") +
  theme(legend.title = element_blank()) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), 
      legend.title = element_blank(), 
      legend.position = c(0.8, 0.2), 
      legend.key=element_rect(fill="white"), legend.text = element_text(size=14),   axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14)) +
  xlim(0,1.5) + ylim(0,1.5) + xlab(bquote(~r[g]*" (KCPS2-BBJ)"))+ ylab(bquote(~r[g]*" (KCPS2-UKB)"))

u2 <- df_res01 %>%
  ggscatter(x="rg.twb",y="rg.ukb", size = 5, 
            label = "p1", repel = TRUE)+ 
  ggpubr::theme_pubr(border = TRUE) + theme(legend.position = "none") +
  geom_abline(intercept = 0, slope = 1, linetype="dotted") + 
  geom_errorbar(aes(ymin = rg.ukb-1.96*se.ukb, ymax = rg.ukb+1.96*se.ukb), col="grey80") + 
  geom_errorbarh(aes(xmin = rg.twb-1.96*se.twb, xmax = rg.twb+1.96*se.twb), col="grey80") +
  theme(legend.title = element_blank()) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), 
      legend.title = element_blank(), 
      legend.position = c(0.8, 0.2), 
      legend.key=element_rect(fill="white"), legend.text = element_text(size=14),   axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14)) +
  xlim(0,1.5) + ylim(0,1.5) + xlab(bquote(~r[g]*" (KCPS2-TWB)"))+ ylab(bquote(~r[g]*" (KCPS2-UKB)"))


u3 <- df_res01 %>%
  ggscatter(x="rg.koges",y="rg.ukb", size = 5, 
            label = "p1", repel = TRUE)+ 
  ggpubr::theme_pubr(border = TRUE) + theme(legend.position = "none") +
  geom_abline(intercept = 0, slope = 1, linetype="dotted") + 
  geom_errorbar(aes(ymin = rg.ukb-1.96*se.ukb, ymax = rg.ukb+1.96*se.ukb), col="grey80") + 
  geom_errorbarh(aes(xmin = rg.koges-1.96*se.koges, xmax = rg.koges+1.96*se.koges), col="grey80") +
  theme(legend.title = element_blank()) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), 
      legend.title = element_blank(), 
      legend.position = c(0.8, 0.2), 
      legend.key=element_rect(fill="white"), legend.text = element_text(size=14),   axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14)) +
  xlim(0,1.5) + ylim(0,1.5) + xlab(bquote(~r[g]*" (KCPS2-KoGES)"))+ ylab(bquote(~r[g]*" (KCPS2-UKB)"))

#ggarrange(ss2,ss1,ss3,ncol=3, common.legend=T, legend="right", labels = c("A", "B", "C"))
bigu <- ggarrange(plotlist = list(u1, u2, u3), ncol = 3, common.legend=T, legend="right", labels = c("d", "e", "f"))

```

```{r}
df_res_8 <- df_res %>%
  filter(p1 %in% c("HEIGHT","BMI","PLT","RBC","WBC","HB","SBP","DBP"))

summary(df_res_8$rg.bbj)
summary(df_res_8$rg.koges)
summary(df_res_8$rg.twb)
summary(df_res_8$rg.ukb)

sum(df_res_8$p.bbj>=0.05/8)
sum(df_res_8$p.koges>=0.05/8)
sum(df_res_8$p.twb>=0.05/8)
sum(df_res_8$p.ukb>=0.05/8)
```


